# Generated by Django 4.2.4 on 2023-08-24 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt',
            name='message',
        ),
        migrations.AddField(
            model_name='mqtt',
            name='DO',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='Device_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='ORP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='TDS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='Temprature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mqtt',
            name='pH',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
