# Generated by Django 4.2.4 on 2023-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_datapoint_device_parameter_delete_mqtt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='param_value',
            field=models.BooleanField(),
        ),
    ]
