# Generated by Django 4.2.4 on 2023-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_parameter_param_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='param_value',
            field=models.FloatField(),
        ),
    ]
