# Generated by Django 4.2.4 on 2023-08-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_parameter_param_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='data_point',
        ),
        migrations.AddField(
            model_name='parameter',
            name='device',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='myapp.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='timestamp',
            field=models.DateTimeField(default='2023-8-28 10:56:10'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
