# Generated by Django 4.2.4 on 2023-08-28 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_parameter_data_point_parameter_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
