# Generated by Django 4.2.4 on 2023-08-28 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_parameter_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='parameter',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parameter',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='param_type',
            field=models.CharField(max_length=100),
        ),
    ]
