# Generated by Django 4.2.4 on 2023-08-30 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_parameter_timestamp_parameter_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField()),
                ('param_type', models.CharField(max_length=100)),
                ('param_value', models.JSONField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
